const type = {
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  SET_SINGLE_PRODUCT: "SET_SINGLE_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
};
export default type;
